### ISSUE TITLE
Allow clearing cache

### ISSUE THREAD

**Issue by otsaloma** [rinigus/mapbox-gl-qml#31]
Sometimes it's needed to clear the cache, to make sure the maps are up-to-date. This can be done by removing the file, but that's very inconvenient and I'd like to add a button to WhoGo Maps to clear the cache. Is that something you could add to the API? Can you remove or truncate the cache database while a Mapbox GL app is running?

**Comment by rinigus** [comment]
As far as I can see, its not available via QMapboxGL API. Actually, it seems to be missing for all APIs, as far as I understand https://github.com/mapbox/mapbox-gl-native/issues/4376

However, the cache is stored in SQLite database and we do have an access to the location of the file. So, it should be quite easy to open it on Qt side and `DELETE` & `VACUUM` tiles on request. SQLite supports access from multiple processes and, since we work with the local file (not NFS), we should be fine if we just access it outside of Mapbox GL API and cleanup as needed.

From the quick look into the .schema of the database, it seems that we can surely delete it all. Maybe via `url` field it would be possible to drop data only from some specified source, but I haven't checked out the data to back it up.

I will look into it.

**Comment by otsaloma** [comment]
Thanks. And, for me, it would be enough to just clear the whole database – deleting URL matches could be useful, but not necessary.

**Comment by rinigus** [comment]
I have added a method `clearCache` that performs full wipe for the cache. If we need later to select which URLs to keep, this can be added too.

You could already use the new widget if you get it from OBS: https://build.merproject.org/package/show/home:rinigus:maps/mapboxgl-qml . This includes your change for integer zooms and clearCache method.

I will look into the filter issue tomorrow.
