### ISSUE TITLE
Make a distinction between swipe and tap

### ISSUE THREAD

**Issue by otsaloma** [rinigus/mapbox-gl-qml#32]
Currently when I tap, e.g. a POI icon on the map, the map usually moves a little bit, which I assume means that the tap is detected as both a swipe (pan) and a tap. It looks quite distracting. Can you make a distinction between these – some kind tolerance that a swipe has to cross? For comparison, QtLocation gets this right.

**Comment by rinigus** [comment]
Unless I figure out how to get map guesture area from QtLocation ported to this plugin (https://github.com/rinigus/mapbox-gl-qml/issues/24), interaction is guided by https://github.com/rinigus/mapbox-gl-qml/blob/master/src/plugin/MapboxMapGestureArea.qml . 

Porting QtLocation map interaction was rather non-trivial. There is a lot of interaction between different components that are absent or replaced in this plugin. In particular, since this plugin is Mapbox GL centered, lots of abstractions were not needed. However, I would expect that lots of work has been done on Qt side to make it feel just right. So, I may try to look into it again and see if I can carry it over in some form. But it may take some time before I can look into it and I am not 100% sure I can do it in reasonable amount of time.

Currently, probably the best would be to change MapboxMapGestureArea.qml in a way that such mixing would not occur. Should be possible, just would have to figure out how and what would be tolerances. Do you want to look into it?

**Comment by otsaloma** [comment]
I could take a look at `MapboxMapGestureArea.qml`, but I'll first do the remaining stuff on the WhoGo Maps side, so it could be a while.

**Comment by rinigus** [comment]
Good. Let's see who gets there first
